### ISSUE TITLE
Abfrage von PICA+ Feldern mit Occurrence

### ISSUE THREAD

**Issue by nichtich** [gbv/PicaHelpRest#2]
Zum Beispiel `022A/00`, `022A/01`, `045B/00`...

Ist nur relevant für Level 0 (und ggf. 1?), da bei Level 2 die Ocurrence als Exemplarzähler dient.

**Comment by nichtich** [comment]
Statt in "tag" sollte die occurence, falls vorhanden in einem eigenen Feld stehen:

~~~json
{
    "tag": "022A",
    "occurrence": "01",
    "pica3": "3211",
 ...
~~~

**Comment by Teralios** [comment]
Problem ist dabei - ist mir auch aufgefallen - dass in solche Fällen sich oft die Pica3 Felder unterscheiden.

Ich hab es jetzt so gelöst, dass man nun im JSON folgendes hat:
```
{
    "022A": {
        "0": {
            "tag": "022A",
            ...
```

**Comment by Teralios** [comment]
Erledigt
