### ISSUE TITLE
Regelmäßige vollständige Dumps

### ISSUE THREAD

**Issue by nichtich** [gbv/PicaHelpRest#7]
Eine vollständige Liste aller Felder (so wie unter `rda/`) *mit* allen Details (Unterfelder...) sollte als JSON-Datei bereitgestellt werden. Dafür ist eine zusätzliche Funktion notwendig, die per Cronjob regelmäßig angestoßen werden kann und die JSON-Datei aktualisiert.

Da Speicherplatz in diesem Fall zu vernachlässigen ist, könnten die Dumps gleich mit Datum versehen archiviert werden (d.h. jeweils eine neue Datei anlegen), so dass später rekunstruiert werden kann, was sich geändert hat. Auf der Startseite könnten z.B. auf neue und geänderte Felder hingewiesen werden.

**Comment by Teralios** [comment]
Als schema aufruf eingebaut.
